name: valorantclient
description: Valorant Client Endpoints for flutter-dart integration.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  path: ^1.8.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
